"""uppt

Revision ID: dfb37bbffce6
Revises: 63ca0621c8f8
Create Date: 2026-06-19 02:49:34.358948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb37bbffce6'
down_revision: Union[str, Sequence[str], None] = '63ca0621c8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('current_status', sa.Enum('ACTIVE', 'PAUSED', name='campaign_status_enum'), nullable=False),
    sa.Column('target_status', sa.Enum('ACTIVE', 'PAUSED', name='campaign_status_enum'), nullable=True),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('budget_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('spend_today', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_days_left', sa.Integer(), nullable=True),
    sa.Column('stock_days_min', sa.Integer(), nullable=True),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_schedules_campaign_id'), 'campaign_schedules', ['campaign_id'], unique=False)
    op.create_table('campaign_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('triggered_rule', sa.String(), nullable=True, comment='Название правила, которое вызвало изменение (null = ручное изменение)'),
    sa.Column('previous_target', sa.Enum('ACTIVE', 'PAUSED', name='campaignstatus'), nullable=True),
    sa.Column('new_target', sa.Enum('ACTIVE', 'PAUSED', name='campaignstatus'), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False, comment='Снапшот данных на момент вычисления: расход, остатки и т.д.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_status_history_campaign_id'), 'campaign_status_history', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_status_history_campaign_id'), table_name='campaign_status_history')
    op.drop_table('campaign_status_history')
    op.drop_index(op.f('ix_campaign_schedules_campaign_id'), table_name='campaign_schedules')
    op.drop_table('campaign_schedules')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
